---
title: "R Notebook"
output: html_document
---

```{r setup}
library(tidyverse)
# library(dbplyr)
library(readr)
library(magrittr)
library(data.table)
library(dtplyr)
library(feather)
library(lubridate)
library(stringr)
library(DBI)
library(RPostgreSQL)
library(RcppRoll)
library(viridis)
```


```{r}
data_dir <- "../data/"
t_dir <- paste0(data_dir, "Transactions/")
t_files <- dir(t_dir)

missing_dir <- paste0(data_dir, "MISSING_TRANSACTIONS/")
missing_files <- dir(missing_dir)

lookup_dir <- paste0(
  data_dir,
  "Lookups/")

lookup_data <- list()
lookup_files <- dir(lookup_dir)
```

```{r}
# transactions <- read_feather("../data/transactions.feather")
# fwrite(transactions, file = "../data/transactions_consolidated.csv", sep = ";")
# t_files %>%
#   map_df(~fread(
#     file = paste0(t_dir, .))) ->
#   transactions
# 
# missing_files %>%
#   map_df(~fread(
#     file = paste0(missing_dir, .))) ->
#   missing_transactions
# 
# missing_transactions %>% 
#   mutate(IsDeferredScript = as.numeric(IsDeferredScript)) -> 
#   missing_transactions
# 
# fwrite(
#   missing_transactions,
#   file = "../data/missing_transactions_consolidated.csv",
#   sep = ";")
# # 
# lookup_files %>%
#   map(~fread(
#     file = paste0(lookup_dir, .)
#   )) %>%
#   walk2(.y = list("atc", "chronic_illnesses", "drugs", "patients", "stores"),
#         ~assign(x = .y, value = .x, envir = .GlobalEnv))
```

```{r}
# transactions <- read_feather("../data/transactions.feather")
# transactions <- read_feather("../data/transactions_sample.feather")
```

```{r}
db <- DBI::dbConnect(RPostgreSQL::PostgreSQL(), dbname = "datathon")
db <- src_postgres(dbname = "datathon")
# db_src <- src_dbi(db)
db_tables <- src_tbls(db)

db_tables %>% 
  walk(~assign(., tbl(db, .), envir = .GlobalEnv))
```

```{r}
atc_local <- atc %>% collect
drugs_local <- drugs %>% collect
```

```{r}
any_matching <- function(v, x) {
  map(x, ~str_detect(tolower(v), .)) %>% 
    reduce(`|`) %>% 
    return()
}

atc_local %>% 
  gather(key, value, -ATCLevel5Code, -ATCLevel5Name) %>% 
  filter(value %>%
           any_matching(c("bacteria", "biotic"))
         ) %>% 
  distinct(ATCLevel5Code) %>% 
  inner_join(atc_local) %>% 
  filter(
    ATCLevel2Name != "ANTIVIRALS FOR SYSTEMIC USE",
    ATCLevel2Name != "VACCINES"
  ) -> 
  atc_antibiotics

```


```{r}
# transactions %>%
#   left_join(drugs,
#             by = c("Drug_Code" = "MasterProductCode")) %>%
#   left_join(atc) %>%
#   semi_join(atc_antibiotics, copy = TRUE) %>%
#   collect(n = Inf) ->
#   antibiotic_transactions
# 
# write_feather(antibiotic_transactions, "../data/antibiotic_transactions.feather")
antibiotic_transactions <- read_feather("../data/antibiotic_transactions.feather")
# fwrite(antibiotic_transactions, "../data/antibiotic_transactions.csv")
```

```{r}
antibiotic_transactions %>% 
  count(ATCLevel5Name) %>% 
  View
```

```{r}
antibiotic_transactions %>% 
  count(Patient_ID) %>%
  count(n) %>%
  View
```

```{r}
antibiotic_transactions %>% 
  count(Prescriber_ID) %>% 
  count(n) %>% 
  View
```

```{r}
antibiotic_transactions %>% 
  count(FormCode)
```

```{r}
antibiotic_transactions %>% 
  count(ATCLevel3Name) %>% 
  filter(n > 1e4) -> 
  top_antibiotics
```
  
```{r}
antibiotic_transactions %>% 
  rename(prescription_week = Prescription_Week,
         dispense_week = Dispense_Week) %>% 
  mutate_at(c("prescription_week", "dispense_week"), ymd) %>% 
  semi_join(top_antibiotics) %>% 
  rename(atc_level_3_name = ATCLevel3Name) ->  
  top_antibiotic_transactions

tat <- top_antibiotic_transactions %>% 
  mutate(atc3 = atc_level_3_name)
```

```{r}
top_antibiotic_transactions %>%
  count(dispense_week, atc_level_3_name) %>% 
  ggplot(aes(x = dispense_week, y = n, colour = atc_level_3_name)) +
  geom_line()
```
```{r}
top_antibiotic_transactions %>% 
  count(atc_level_3_name, dispense_week) %>% 
  group_by(atc_level_3_name) %>% 
  mutate(rn = roll_mean(n, n = 4L, fill = 0, align = "center", na.rm = T)) %>% 
  ggplot(aes(x = dispense_week, y = rn, colour = atc_level_3_name)) +
  geom_line()
```

```{r}
any_matching <- function(v, x) {
  map(x, ~str_detect(tolower(v), .)) %>% 
    reduce(`|`) %>% 
    return()
}

top_antibiotic_transactions %>% 
  filter(atc_level_3_name %>%
           any_matching(c("penic", "macrolides"))) %>%
  filter(prescription_week %>% 
           between(
             ymd("2011-01-01"),
             ymd("2015-12-31")
           )
         ) %>% 
  count(atc_level_3_name, prescription_week) %>% 
  group_by(atc_level_3_name) %>% 
  mutate(rn = roll_mean(n, n = 4L, fill = 0, align = "center", na.rm = T)) %>% 
  ggplot(aes(x = prescription_week, y = rn, colour = atc_level_3_name)) +
  geom_line()
```

```{r}
tat %>% 
  count(atc_level_3_name, ATCLevel4Name, ATCLevel5Name) %>% 
  group_by(atc_level_3_name) %>% 
  mutate(level_3_count = sum(n)) %>% 
  ungroup %>% 
  arrange(level_3_count %>% desc, n %>% desc) %>% 
  View
```


```{r}
tat %>% 
  count(atc_level_3_name, RepeatsTotal_Qty) %>% 
  filter(RepeatsTotal_Qty < 10) %>% 
  mutate_at("RepeatsTotal_Qty", . %>% as.numeric %>% as.factor) %>% 
  ggplot(aes(x = atc_level_3_name, fill = RepeatsTotal_Qty, y = n)) +
  geom_col(postition = "dodge") +
  coord_flip()
```

```{r}
tat %>% 
  count(ATCLevel5Name, NHS_Code) %>% 
  ungroup %>% 
  arrange(n %>% desc) %>% 
  filter(!is.na(NHS_Code)) %>% 
  slice(1:50) -> 
  ab_most_prescribed
```

```{r}
tat %>% 
  semi_join(ab_most_prescribed) %>% 
  count(atc_level_3_name, NHS_Code, RepeatsTotal_Qty) -> 
  repeat_numbers
```

```{r}
tat %>% 
  count(ATCLevel5Name) %>% 
  View
```

```{r}
tat %>% 
  filter(prescription_week %>% 
           between(
             ymd("2011-01-01"),
             ymd("2015-12-31")
           )
  ) %>% 
  semi_join(
    (.) %>% 
      count(ATCLevel5Name) %>% 
      ungroup %>% 
      arrange(n %>% desc) %>% 
      slice(1:20)
  ) %>% 
  count(prescription_week, ATCLevel5Name) %>% 
  group_by(ATCLevel5Name) %>% 
  mutate(frac = n / sum(n)) %>% 
  ggplot(aes(x = prescription_week, colour = ATCLevel5Name, y = frac)) +
  geom_line() +
  facet_wrap(~ATCLevel5Name)
```

```{r}
tat %>% 
  filter(dispense_week %>% 
           between(
             ymd("2011-01-01"),
             ymd("2015-12-31")
           )
  ) %>% 
  semi_join(
    (.) %>% 
      count(ATCLevel5Name) %>% 
      ungroup %>% 
      arrange(n %>% desc) %>% 
      slice(1:20)
  ) %>% 
  count(dispense_week, ATCLevel5Name) %>% 
  group_by(ATCLevel5Name) %>% 
  mutate(frac = n / sum(n)) %>% 
  ggplot(aes(x = dispense_week, colour = ATCLevel5Name, y = frac)) +
  geom_line() +
  facet_wrap(~ATCLevel5Name)
```

```{r}
tat %>% 
  count(Prescriber_ID) %>%
  ungroup %>% 
  count(n) %>% 
  View
```

